#!/bin/bash

echo "Activating NodeEnv..."

freeze () {
    local NPM_VER=`npm -v | cut -d '.' -f 1`
    local re="[a-zA-Z0-9\.\-]+@[0-9]+\.[0-9]+\.[0-9]+([\+\-][a-zA-Z0-9\.\-]+)*"
    if [ "$NPM_VER" = '0' ]; then
        NPM_LIST=`npm list installed active 2>/dev/null | cut -d ' ' -f 1 | grep -v npm`
    else
        local npmls="npm ls -g"
        if [ "$1" = "-l" ]; then
            npmls="npm ls"
            shift
        fi
        NPM_LIST=$(eval ${npmls} | grep -E '^.{4}\w{1}'| grep -o -E "$re"| grep -v npm)
    fi

    if [ -z "$@" ]; then
        echo "$NPM_LIST"
    else
        echo "$NPM_LIST" > $@
    fi
}

set_variable NODE_VIRTUAL_ENV NODE_VIRTUAL_ENV '$VIRTUAL_ENV'
set_variable NODE_PATH NODE_PATH '$NODE_VIRTUAL_ENV/lib/node_modules'
set_variable NPM_CONFIG_PREFIX NPM_CONFIG_PREFIX '$NODE_VIRTUAL_ENV'
set_variable npm_config_prefix npm_config_prefix '$NODE_VIRTUAL_ENV'
