#!/bin/bash

echo "Deactivating VirtualEnv..."

unset pydoc

# reset old environment variables
restore_variable PYHOME PYHOME
restore_variable PATH VIRTUAL_PATH
restore_variable PYTHONHOME VIRTUAL_PYTHONHOME

# This should detect bash and zsh, which have a hash command that must
# be called to get it to forget past commands.  Without forgetting
# past commands the $PATH changes we made may not be respected
if [ -n "${BASH-}" -o -n "${ZSH_VERSION-}" ] ; then
  hash -r 2>/dev/null
fi

restore_variable PS1 VIRTUAL_PS1
